module.exports = {
  checkAll: "Check All",
  close: "Close",
  addCurrent: "Add Current",
  confirmPrepayment: "Confirm Prepayment",
  totalPrice: "Total Price",
  channelType: "Channel",
  channelArea: "Channel Area",
  selected: "Selected",
  disable: "Disable",
  enable: "Enable",
  successMsg: "Success!",
  failMsg: "Fail!",
  batchImport: "Bulk Import",
  country: "Country",
  billView: "Bill Preview",
  price: "Price",
  reason: "Reason",
  type: "Type",
  passenger: "Person",
  repriceTypes: {
    TICKET: "Ticket Fee",
    CHARGE: "Port Charge",
    PORTTRAVEL: "Shore-ex additional fee",
    CUSTOM: "Name change fee",
  },
  cnyPersonUnit: "{0}CNY/per pax",
  shoreEx: "Shore-ex",
  delete: "Delete",
  deleteConfirm: "Are you sure delete this?",
  add: "Add",
  action: "Action",
  priceComparison: "Price Comparison",
  addBed: "Rollaway Bed",
  passengerInfo: "Passenger Info",
  totalPerson: "total pax",
  voyageCode: "Cruise ID",
  orderId: "Order ID",
  productName: "Itinarary",
  orderFrom: "Distributor",
  orderStatus: "Status",
  createdAt: "Create Time",
  contact: "Contact",
  orderType: "Booking Type",
  totalPrice: "Total Amount",
  remark: "Remark",
  cutCabin: "Type of Block",
  cutCabinSoft: "Soft Block",
  cutCabinHard: "Buyout",
  charterShip: "Charter",
  commission: "Commission",
  harbourDues: "Port Charge",

  refund: "Cancel fee",
  creater: "Grp Request",
  groupType: "Group Type",

  groupOrder: "Group Order",
  fitOrder: "FIT Order",
  edit: "Edit",
  confirm: "Confirm",
  travelAgencyTotal: "Total amount (excl. commission)",
  groupDepositPayment: "Deposit Payment Notice",
  fitDepositPayment: "FIT Payment Notice",
  download: "Download",
  downloadSuccessMsg: "Download Success!",
  reprice: "Reprice",
  pushBill: "Submit Bill",
  doubleCheckText: "Confirm execution?",
  unsold: "Unsold",
  rooms: "{0} rooms",
  confirm: "Confirm",
  cancel: "Cancel",
  spend: "Spend",
  save: "Save",
  confirmZeroDeposit: "Confirm ￥0 deposit.",
  confirmSettle: "Confirm Settlement",
  addPassenger: "Add Passenger",
};

/* 
1. 导出excel  （读js文件，excel.js 导出）
2. 用户修改完成后，将excel 内容 覆盖到该文件（读excel文件， sheet1 表格， 读行一  行二， 读取生成json 导入回原始文件。（新建一个newCn。js 导入）
https://github.com/exceljs/exceljs/blob/HEAD/README_zh.md#%E5%88%9B%E5%BB%BA%E5%B7%A5%E4%BD%9C%E7%B0%BF



*/
